### PR TITLE
Supports the filterMapper and additional header filters

### PR DESCRIPTION
**Pull request by Onomanatee**
See temp PR for HUVESRV-23 for the other side of this implementation

### CODE REVIEW

**Comment by gboston** [comment]
bump version

**Comment by Onomanatee** [comment]
@gboston bumped version

**Comment by Onomanatee** [comment]
Goddamn close and comment button is to close to the comment button

**Comment by Onomanatee** [comment]
NOTE: This PR should NOT be merged untill feature/HUVESRV-23 is ready to merge

**Pull request merged**
